### PR TITLE
psalm fix, replaced deprecated fuction call

### LINKED ISSUE #46: Replace usage of `twig_date_converter` with own solution
**The issue:**
- Function 'twig_date_converter' is deprecated
- Function 'twig_date_converter' is marked as @ internal

**Where:**
File: `src/Extension/DateExtension.php`
Lines: `43`-`44`

**Recommendation from vendor:**
_None_

**Todo:**
- Find a solution to achieve the same results with our own function directly in the `DateExtension` class.
- Remove file `psalm-baseline.xml`
- Remove line `errorBaseline="psalm-baseline.xml"` from `psalm.xml`

### PR DESCRIPTION
**Pull request by Jurj-Bogdan**
update for problem found in PR #47

### CODE REVIEW

File: psalm.xml [hunk 1]
```diff
@@ -7,7 +7,6 @@
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="https://getpsalm.org/schema/config"
         xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
-        errorBaseline="psalm-baseline.xml"
```
Comment (alexmerlin) [inline psalm.xml:10]: If you removed `errorBaseline` and emptied `psalm-baseline.xml` you should remove `psalm-baseline.xml` as it's no longer in use.

**Review by alexmerlin — CHANGES_REQUESTED** [review]

**Review by alexmerlin — APPROVED** [review]

**Comment by alexmerlin** [comment]
@Jurj-Bogdan Why merge PR into the `ossbadge` branch?

**Comment by Jurj-Bogdan** [comment]
> @Jurj-Bogdan Why merge PR into the `ossbadge` branch?

The initial commit was meant as a fix for @bidi47's PR #47, but the fix also failed the CI checks because of the problem found in issue #46
